import 'package:flutter/material.dart';
import 'package:otzaria/l10n/app_localizations.dart';

export 'package:otzaria/l10n/app_localizations.dart';

extension AppLocalizationsBuildContext on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);

  bool get isEnglishMode => l10n.localeName == 'en';

  String trLiteral(String text) {
    if (!isEnglishMode) return text;
    final direct = _lookupLiteralTranslation(l10n, text);
    if (direct != text) return direct;

    const categorySearchPrefix = 'חיפוש בקטגוריות: ';
    if (text.startsWith(categorySearchPrefix)) {
      return 'Search in categories: ${text.substring(categorySearchPrefix.length)}';
    }

    const copyErrorPrefix = 'שגיאה בהעתקה: ';
    if (text.startsWith(copyErrorPrefix)) {
      return 'Copy error: ${text.substring(copyErrorPrefix.length)}';
    }

    return text;
  }

  Widget translateTextWidget(Widget widget) {
    if (widget is! Text || widget.data == null) {
      return widget;
    }

    return Text(
      trLiteral(widget.data!),
      key: widget.key,
      style: widget.style,
      strutStyle: widget.strutStyle,
      textAlign: widget.textAlign,
      textDirection: widget.textDirection,
      locale: widget.locale,
      softWrap: widget.softWrap,
      overflow: widget.overflow,
      textScaler: widget.textScaler,
      maxLines: widget.maxLines,
      semanticsLabel: widget.semanticsLabel,
      textWidthBasis: widget.textWidthBasis,
      textHeightBehavior: widget.textHeightBehavior,
      selectionColor: widget.selectionColor,
    );
  }

  String t(String key) {
    return switch (key) {
      'app.title' => l10n.appTitle,
      'settings.title' => l10n.settingsTitle,
      'settings.back' => l10n.settingsBack,
      'settings.tab.design' => l10n.settingsTabDesign,
      'settings.tab.text' => l10n.settingsTabText,
      'settings.tab.library' => l10n.settingsTabLibrary,
      'settings.tab.tools' => l10n.settingsTabTools,
      'settings.tab.shortcuts' => l10n.settingsTabShortcuts,
      'settings.tab.system' => l10n.settingsTabSystem,
      'settings.tab.about' => l10n.settingsTabAbout,
      'settings.group.displayContent' => l10n.settingsGroupDisplayContent,
      'settings.group.tools' => l10n.settingsGroupTools,
      'settings.group.system' => l10n.settingsGroupSystem,
      'settings.language.cardTitle' => l10n.settingsLanguageCardTitle,
      'settings.language.title' => l10n.settingsLanguageTitle,
      'settings.language.subtitle.he' => l10n.settingsLanguageSubtitleHe,
      'settings.language.subtitle.en' => l10n.settingsLanguageSubtitleEn,
      'settings.language.hebrew' => l10n.settingsLanguageHebrew,
      'settings.language.english' => l10n.settingsLanguageEnglish,
      'settings.language.restartHint' => l10n.settingsLanguageRestartHint,
      _ => key,
    };
  }
}

String _lookupLiteralTranslation(AppLocalizations l10n, String text) {
  return switch (text) {
    'הגדרות' => l10n.literalTranslation001,
    'מראה' => l10n.literalTranslation002,
    'כתב' => l10n.literalTranslation003,
    'ספריה' => l10n.literalTranslation004,
    'כלים' => l10n.literalTranslation005,
    'קיצורים' => l10n.literalTranslation006,
    'מערכת' => l10n.literalTranslation007,
    'אודות' => l10n.literalTranslation008,
    'תצוגה ותוכן' => l10n.literalTranslation009,
    'חזור (Backspace)' => l10n.literalTranslation010,
    'תצוגה' => l10n.literalTranslation011,
    'מסך מלא' => l10n.literalTranslation012,
    'החלף מצב מסך מלא' => l10n.literalTranslation013,
    'ערכת נושא' => l10n.literalTranslation014,
    'מעקב אחר צבע המערכת' => l10n.literalTranslation015,
    'מופעל' => l10n.literalTranslation016,
    'לא מופעל' => l10n.literalTranslation017,
    'מצב כהה' => l10n.literalTranslation018,
    'צבע בסיס' => l10n.literalTranslation019,
    'כרטיסיות הספרים' => l10n.literalTranslation020,
    'תפריטים קומפקטיים' => l10n.literalTranslation021,
    'התפריטים יוצגו בצפיפות עבודה בסגנון Chrome' => l10n.literalTranslation022,
    'התפריטים יוצגו במרווח נוח ובגרסה הרגילה' => l10n.literalTranslation023,
    'הצגת כרטיסיות בימין' => l10n.literalTranslation024,
    'הכרטיסיות יהיו בצד ימין' => l10n.literalTranslation025,
    'הכרטיסיות יהיו במרכז החלון' => l10n.literalTranslation026,
    'חלוניות עזר' => l10n.literalTranslation027,
    'חלונית ניווט בין כותרות' => l10n.literalTranslation028,
    'החלונית תוצג באופן קבוע' => l10n.literalTranslation029,
    'החלונית תוצג בפתיחת ספר ותיסגר בעת גלילה' => l10n.literalTranslation030,
    'החלונית לא תוצג אוטומטית עם פתיחת הספר' => l10n.literalTranslation031,
    'הצגה' => l10n.literalTranslation032,
    'אוטומטי' => l10n.literalTranslation033,
    'הסתרה' => l10n.literalTranslation034,
    'הסתרת הערות אישיות' => l10n.literalTranslation035,
    'רשימות ההערות ייפתחו במצב סגור' => l10n.literalTranslation036,
    'רשימות ההערות ייפתחו במצב פתוח' => l10n.literalTranslation037,
    'הצגת המפרשים בחלונית בצד' => l10n.literalTranslation038,
    'המפרשים יוצגו בחלונית מפוצלת' => l10n.literalTranslation039,
    'המפרשים יוצגו בתוך הטקסט' => l10n.literalTranslation040,
    'הגדרות גופן ועיצוב' => l10n.literalTranslation041,
    'גודל גופן הספר' => l10n.literalTranslation042,
    'גופן טקסט' => l10n.literalTranslation043,
    'גודל גופן מפרשים' => l10n.literalTranslation044,
    'גופן מפרשים' => l10n.literalTranslation045,
    'מרווח בין שורות' => l10n.literalTranslation046,
    'כתרי אותיות' => l10n.literalTranslation047,
    'הצגת הניקוד' => l10n.literalTranslation048,
    'הניקוד יוצג בכל הספרים' => l10n.literalTranslation049,
    'הניקוד יוצג בספרי התנ"ך בלבד' => l10n.literalTranslation050,
    'הניקוד לא יוצג בכלל' => l10n.literalTranslation051,
    'הצג תמיד' => l10n.literalTranslation052,
    'הצג בתנ"ך' => l10n.literalTranslation053,
    'אל תציג' => l10n.literalTranslation054,
    'הצגת שם הקודש' => l10n.literalTranslation055,
    'השם הקדוש יוצג' => l10n.literalTranslation056,
    'השם הקדוש לא יוצג מפני קדושתו' => l10n.literalTranslation057,
    'הצגת טעמי המקרא' => l10n.literalTranslation058,
    'המקרא יוצג עם טעמים' => l10n.literalTranslation059,
    'המקרא יוצג ללא טעמים' => l10n.literalTranslation060,
    'הגדרות העתקה' => l10n.literalTranslation061,
    'העתקה עם כותרות' => l10n.literalTranslation062,
    'ללא' => l10n.literalTranslation063,
    'שם הספר בלבד' => l10n.literalTranslation064,
    'שם הספר+נתיב' => l10n.literalTranslation065,
    'עיצוב העתקה' => l10n.literalTranslation066,
    'אותה שורה אחרי (עם סוגריים)' => l10n.literalTranslation067,
    'אותה שורה אחרי (בלי סוגריים)' => l10n.literalTranslation068,
    'אותה שורה לפני (עם סוגריים)' => l10n.literalTranslation069,
    'אותה שורה לפני (בלי סוגריים)' => l10n.literalTranslation070,
    'פסקה נפרדת אחרי' => l10n.literalTranslation071,
    'פסקה נפרדת לפני' => l10n.literalTranslation072,
    'הגדרות לפי ספר' => l10n.literalTranslation073,
    'שמירת התאמות לכל ספר בנפרד' => l10n.literalTranslation074,
    'שינויים בסרגל הלחצנים יישמרו לכל ספר בנפרד' => l10n.literalTranslation075,
    'כל הספרים ישתמשו בהגדרות הכלליות' => l10n.literalTranslation076,
    'אפס את כל הגדרות אלו, בכל הספרים' => l10n.literalTranslation077,
    'מלא' => l10n.literalTranslation078,
    'רוחב הטקסט' => l10n.literalTranslation079,
    'הטקסט ימלא את כל הרוחב הזמין' => l10n.literalTranslation080,
    'הטקסט יהיה צר יותר ומרוכז במסך' => l10n.literalTranslation081,
    'תצוגת ספרייה' => l10n.literalTranslation082,
    'סוג תצוגה' => l10n.literalTranslation083,
    'רשת' => l10n.literalTranslation084,
    'רשימה' => l10n.literalTranslation085,
    'תצוגת רשת' => l10n.literalTranslation086,
    'תצוגת רשימה (עץ מתרחב)' => l10n.literalTranslation087,
    'הצג תצוגה מקדימה' => l10n.literalTranslation088,
    'תצוגה מקדימה מוצגת' => l10n.literalTranslation089,
    'תצוגה מקדימה מוסתרת' => l10n.literalTranslation090,
    'ספרים נוספים' => l10n.literalTranslation091,
    'הצגת ספרים מאתרים חיצוניים' => l10n.literalTranslation092,
    'יוצגו גם ספרים מאתרים חיצוניים' => l10n.literalTranslation093,
    'יוצגו רק ספרים מספריית אוצריא' => l10n.literalTranslation094,
    'הצג ספרים מאוצר החכמה' => l10n.literalTranslation095,
    'ספרים מאתר אוצר החכמה' => l10n.literalTranslation096,
    'הצג ספרים מהיברובוקס' => l10n.literalTranslation097,
    'ספרים מאתר HebrewBooks' => l10n.literalTranslation098,
    'סנכרון קטלוגים אוטומטי' => l10n.literalTranslation099,
    'עדכן קטלוגים חיצוניים אוטומטית' => l10n.literalTranslation100,
    'מאגר הספרים' => l10n.literalTranslation101,
    'תיקיות מותאמות אישית' => l10n.literalTranslation102,
    'חיפוש ואינדקס' => l10n.literalTranslation103,
    'עדכון אינדקס אוטומטי' => l10n.literalTranslation104,
    'אינדקס החיפוש יתעדכן אוטומטית' => l10n.literalTranslation105,
    'אינדקס החיפוש לא יתעדכן אוטומטית' => l10n.literalTranslation106,
    'לא קיימת ספרייה לאינדוקס' => l10n.literalTranslation107,
    'הספרייה ריקה – אין ספרים לאינדוקס' => l10n.literalTranslation108,
    'האינדקס מעודכן' => l10n.literalTranslation109,
    'האינדקס לא מעודכן' => l10n.literalTranslation110,
    'אינדקס חיפוש' => l10n.literalTranslation111,
    'עצור' => l10n.literalTranslation112,
    'איפוס' => l10n.literalTranslation113,
    'עדכן' => l10n.literalTranslation114,
    'עדכוני מערכת' => l10n.literalTranslation115,
    'סינכרון ומצב רשת' => l10n.literalTranslation116,
    'התוכנה מנותקת לגמרי מהרשת' => l10n.literalTranslation117,
    'התוכנה יכולה להתחבר לרשת' => l10n.literalTranslation118,
    'מקוון' => l10n.literalTranslation119,
    'מנותק' => l10n.literalTranslation120,
    'עדכוני תוכנה וספרים' => l10n.literalTranslation121,
    'מושבת במצב מנותק' => l10n.literalTranslation122,
    'סינכרון הספרייה באופן אוטומטי' => l10n.literalTranslation123,
    'מסד הנתונים של הספרייה יתעדכן אוטומטית' => l10n.literalTranslation124,
    'סינכרון הספרייה מושבת' => l10n.literalTranslation125,
    'עדכון לגרסאות מפתחים' => l10n.literalTranslation126,
    'קבלת עדכונים על גרסאות בדיקה — ייתכנו באגים' => l10n.literalTranslation127,
    'קבלת עדכונים על גרסאות יציבות בלבד' => l10n.literalTranslation128,
    'דיווחי טעויות' => l10n.literalTranslation129,
    'שליחה ישירה לצוות אוצריא, כולל תור אוטומטי במצב אופליין.' =>
      l10n.literalTranslation130,
    'כתובת מייל לזיהוי' => l10n.literalTranslation131,
    'עדיין לא הוגדרה כתובת זיהוי' => l10n.literalTranslation132,
    'נקה' => l10n.literalTranslation133,
    'הגדר' => l10n.literalTranslation134,
    'ערוך' => l10n.literalTranslation135,
    'שמירת דיווחים אוטומטית כשאין חיבור' => l10n.literalTranslation136,
    'ניהול דיווחים שמורים' => l10n.literalTranslation137,
    'אין כרגע דיווחים שמורים בתור' => l10n.literalTranslation138,
    'שלח עכשיו' => l10n.literalTranslation139,
    'נקה דיווחים' => l10n.literalTranslation140,
    'הורד לשליחה במחשב מחובר' => l10n.literalTranslation141,
    'מערכת אוצריא' => l10n.literalTranslation142,
    'גרסת תוכנה' => l10n.literalTranslation143,
    'טוען...' => l10n.literalTranslation144,
    'יומן שינויים' => l10n.literalTranslation145,
    'גרסת ספרייה' => l10n.literalTranslation146,
    'מספר ספרים' => l10n.literalTranslation147,
    'לא ידוע' => l10n.literalTranslation148,
    'תורמים' => l10n.literalTranslation149,
    'מתקדם' => l10n.literalTranslation150,
    'גיבוי אוטומטי' => l10n.literalTranslation151,
    'שבועי' => l10n.literalTranslation152,
    'חודשי' => l10n.literalTranslation153,
    'מצב גיבוי' => l10n.literalTranslation154,
    'גבה הכל' => l10n.literalTranslation155,
    'מותאם אישית' => l10n.literalTranslation156,
    'כולל את כלל הגדרות התוכנה' => l10n.literalTranslation157,
    'סימניות' => l10n.literalTranslation158,
    'כל הסימניות שנשמרו' => l10n.literalTranslation159,
    'היסטוריה' => l10n.literalTranslation160,
    'היסטוריית הלימוד' => l10n.literalTranslation161,
    'הערות אישיות' => l10n.literalTranslation162,
    'כל ההערות האישיות שלך' => l10n.literalTranslation163,
    'שולחנות עבודה' => l10n.literalTranslation164,
    'כל שולחנות העבודה' => l10n.literalTranslation165,
    'שמור וזכור' => l10n.literalTranslation166,
    'ספרים ומעקב לימוד' => l10n.literalTranslation167,
    'הגדרות מתקדמות' => l10n.literalTranslation168,
    'הגדרות נוספות שדרסת' => l10n.literalTranslation169,
    'צור גיבוי עכשיו' => l10n.literalTranslation170,
    'שחזר מגיבוי' => l10n.literalTranslation171,
    'מצב סייפר' => l10n.literalTranslation172,
    'נעילת הגדרות' => l10n.literalTranslation173,
    'הפעל מצב סייפר' => l10n.literalTranslation174,
    'סיסמה הוגדרה' => l10n.literalTranslation175,
    'יש להגדיר סיסמה תחילה' => l10n.literalTranslation176,
    'סיסמה' => l10n.literalTranslation177,
    'שנה סיסמה' => l10n.literalTranslation178,
    'בחר סיסמה' => l10n.literalTranslation179,
    'איפוס הגדרות' => l10n.literalTranslation180,
    'מחיקת כל ההגדרות וחזרה למצב ההתחלתי' => l10n.literalTranslation181,
    'אפס הגדרות' => l10n.literalTranslation182,
    'נדרשת הפעלה מחדש' => l10n.literalTranslation183,
    'הספרייה נמצאה בהצלחה.\nלחץ על הכפתור להפעלה מחדש של התוכנה.' =>
      l10n.literalTranslation184,
    'הספרייה נמצאה בהצלחה.\nלחץ על הכפתור לסגירת האפליקציה, ולאחר מכן פתח אותה מחדש.' =>
      l10n.literalTranslation185,
    'הפעל מחדש את התוכנה' => l10n.literalTranslation186,
    'סגור את האפליקציה' => l10n.literalTranslation187,
    'נדרשת העתקה של קובץ הספרייה' => l10n.literalTranslation188,
    'העתק (שמור מקור)' => l10n.literalTranslation189,
    'העתק + נסה מחק מקור' => l10n.literalTranslation190,
    'העתק' => l10n.literalTranslation191,
    'העבר' => l10n.literalTranslation192,
    'פתח מקור' => l10n.literalTranslation193,
    'אחר כך' => l10n.literalTranslation194,
    'סגור עכשיו' => l10n.literalTranslation195,
    'כדי להשלים את השינוי יש לסגור ולהפעיל מחדש את התוכנה. האם לסגור עכשיו?' =>
      l10n.literalTranslation196,
    'נדרשת בחירה כיצד לשמור את מסד הנתונים' => l10n.literalTranslation197,
    'לחץ על כפתור למטה, נווט לאותה תיקייה ובחר את הקובץ seforim.db — האפליקציה תעתיק אותו לאחסון הפנימי.' =>
      l10n.literalTranslation198,
    '(אפשרות "נסה מחק מקור" — ניסיון למחוק לאחר העתקה. עשויה שלא להצליח בכל גרסאות Android.)' =>
      l10n.literalTranslation199,
    'חיפוש...' => l10n.literalTranslation200,
    'הגדרות חיפוש' => l10n.literalTranslation201,
    'לא נמצאו פריטים' => l10n.literalTranslation202,
    'לא נמצאו תוצאות' => l10n.literalTranslation203,
    'חפש בסימניות...' => l10n.literalTranslation204,
    'אין סימניות' => l10n.literalTranslation205,
    'מחק את כל הסימניות' => l10n.literalTranslation206,
    'הסימניה נמחקה' => l10n.literalTranslation207,
    'כל הסימניות נמחקו' => l10n.literalTranslation208,
    'חפש בהיסטוריה...' => l10n.literalTranslation209,
    'אין היסטוריה' => l10n.literalTranslation210,
    'מחק את כל ההיסטוריה' => l10n.literalTranslation211,
    'נמחק בהצלחה' => l10n.literalTranslation212,
    'כל ההיסטוריה נמחקה' => l10n.literalTranslation213,
    'חיפוש' => l10n.literalTranslation214,
    'מזער' => l10n.literalTranslation215,
    'צא ממסך מלא' => l10n.literalTranslation216,
    'הטקסט הועתק ללוח' => l10n.literalTranslation217,
    'הטקסט המעוצב הועתק ללוח' => l10n.literalTranslation218,
    'שגיאה בהעתקה' => l10n.literalTranslation219,
    'שגיאה בהעתקה מעוצבת' => l10n.literalTranslation220,
    'הדף לא נמצא בתוכן העניינים' => l10n.literalTranslation221,
    'הספר איננו קיים' => l10n.literalTranslation222,
    'ההערה נוצרה והוצבה בסרגל' => l10n.literalTranslation223,
    'השינויים נשמרו בהצלחה' => l10n.literalTranslation224,
    'הטקסט לא נמצא' => l10n.literalTranslation225,
    'אנא בחר טקסט להעתקה' => l10n.literalTranslation226,
    'ניקוי טיוטות הושלם' => l10n.literalTranslation227,
    'ביטול' => l10n.literalTranslation228,
    'אישור' => l10n.literalTranslation229,
    'סגור' => l10n.literalTranslation230,
    'מחק' => l10n.literalTranslation231,
    'שמור' => l10n.literalTranslation232,
    _ => text,
  };
}
