// Generates the Torah page layouts from one source, the Or LaSofer tables in
// tool/tikkun_korim/vendor/or_lasofer_layouts.json:
//   lib/tools/tikkun_korim/data/torah_layouts.g.dart       methods and pages
//   lib/tools/tikkun_korim/data/torah_page_anchors.g.dart  each page's anchor
// Each page's first and last word is resolved against the Torah text.
//   flutter test tool/tikkun_korim/generate_torah_layouts_test.dart
// Set ANCHORS_OUT to a directory to also write a report of suspicious pages.
import 'dart:convert';
import 'dart:io';
import 'dart:math' as math;

import 'package:flutter_test/flutter_test.dart';
import 'package:otzaria/tools/tikkun_korim/data/tikkun_data.dart';
import 'package:otzaria/tools/tikkun_korim/engine/official_pages_builder.dart';
import 'package:otzaria/tools/tikkun_korim/engine/stam_width_model.dart';
import 'package:otzaria/tools/tikkun_korim/engine/tikkun_processor.dart';
import 'package:otzaria/tools/tikkun_korim/engine/tokenizer.dart';
import 'package:otzaria/tools/tikkun_korim/models/tikkun_models.dart';

import '../../test/tools/tikkun_korim/support/tikkun_fixtures.dart';

const _source = 'tool/tikkun_korim/vendor/or_lasofer_layouts.json';
const _layoutsOut = 'lib/tools/tikkun_korim/data/torah_layouts.g.dart';
const _anchorsOut = 'lib/tools/tikkun_korim/data/torah_page_anchors.g.dart';
const _header =
    '// generated by tool/tikkun_korim/generate_torah_layouts_test.dart'
    ' — do not edit';

class SourcePage {
  final int num;

  /// May carry a stray label fragment from the PDF; every space-separated
  /// part is tried, and the text decides.
  final String? first;
  final String? last;
  SourcePage(this.num, this.first, this.last);
}

class SourceMethod {
  final String id;
  final String name;
  final String fullName;
  final int linesPerPage;
  final List<SourcePage> pages;
  SourceMethod(
    this.id,
    this.name,
    this.fullName,
    this.linesPerPage,
    this.pages,
  );
}

List<SourceMethod> readSource() {
  final json = jsonDecode(File(_source).readAsStringSync()) as Map;
  return [
    for (final entry in (json['methods'] as Map).entries)
      SourceMethod(
        entry.key as String,
        (entry.value as Map)['name'] as String,
        (entry.value as Map)['fullName'] as String,
        (entry.value as Map)['linesPerPage'] as int,
        [
          for (final p in (entry.value as Map)['pages'] as List)
            SourcePage(
              (p as Map)['num'] as int,
              p['first'] as String?,
              p['last'] as String?,
            ),
        ],
      ),
  ];
}

Iterable<String> parts(String? value) =>
    value == null ? const [] : value.split(' ').where((s) => s.isNotEmpty);

final RegExp _ketivQere = RegExp('\u{E010}([\\s\\S]*?)\u{E011}[\\s\\S]*');
final RegExp _pua = RegExp('[\u{E000}-\u{E0FF}]');
final RegExp _punctuation = RegExp('[.\'׳]');

/// Matching key: the ketiv of a ketiv/qere pair, no zeira/rabati marks, no
/// punctuation, and the tables' substitute spellings of the Name mapped back
/// to the text's ("יקוק", and the abbreviation "ה'" with its prefixes).
String matchKey(String stam) {
  final bare = stam
      .replaceAllMapped(_ketivQere, (m) => m[1]!)
      .replaceAll(_pua, '')
      .replaceAll('יקוק', 'יהוה');
  if (RegExp('^[ולבכמש]*ה[\'׳]\$').hasMatch(bare)) {
    return '${bare.substring(0, bare.length - 2)}יהוה';
  }
  return bare.replaceAll(_punctuation, '');
}

class Word {
  final TikkunWordRef ref;
  final String key;
  Word(this.ref, this.key);
}

List<Word> torahWords(TikkunTradition tradition) {
  final torah = processTorah(
    {for (final id in TikkunData.booksOrder) id: readFixture(id)},
    const StamWidthModel.uniform(),
    tradition: tradition,
  );
  final out = <Word>[];
  forEachTorahWord(torah.tokens, (i, ref) {
    out.add(Word(ref, matchKey(stripNikud(torah.tokens[i].value!))));
  });
  return out;
}

class Cand {
  final int page, pos, weight;
  Cand(this.page, this.pos, this.weight);
}

/// Picks the strictly increasing chain of (page, word) candidates with the most
/// matched evidence and the most plausible page lengths. Lengths are counted
/// in letters: a column holds a near-constant letter count, not word count.
List<int?> resolve(List<SourcePage> pages, List<Word> words) {
  final occ = <String, List<int>>{};
  for (var i = 0; i < words.length; i++) {
    occ.putIfAbsent(words[i].key, () => []).add(i);
  }
  final cum = List<int>.filled(words.length + 1, 0);
  for (var i = 0; i < words.length; i++) {
    cum[i + 1] = cum[i] + visibleStamLen(words[i].key) + 1;
  }
  final avg = cum.last / pages.length;
  // Local densities differ, so the drift from an even spread grows along the
  // scroll; the window is wide and the length penalty does the choosing.
  final window = avg * 12;

  final cands = <Cand>[Cand(0, 0, 0)];
  for (var p = 1; p < pages.length; p++) {
    final expected = p * avg;
    final weights = <int, int>{};
    for (final part in parts(pages[p].first)) {
      for (final i in occ[matchKey(part)] ?? const <int>[]) {
        if ((cum[i] - expected).abs() <= window) weights[i] = 2;
      }
    }
    for (final part in parts(pages[p - 1].last)) {
      for (final i in occ[matchKey(part)] ?? const <int>[]) {
        final b = i + 1;
        if (b < words.length && (cum[b] - expected).abs() <= window) {
          weights[b] = (weights[b] ?? 0) + 2;
        }
      }
    }
    weights.forEach((pos, w) => cands.add(Cand(p, pos, w)));
  }
  cands.sort((a, b) => a.page != b.page ? a.page - b.page : a.pos - b.pos);

  final score = List<double>.filled(cands.length, double.negativeInfinity);
  final back = List<int>.filled(cands.length, -1);
  score[0] = 0;
  for (var j = 1; j < cands.length; j++) {
    final cj = cands[j];
    for (var i = j - 1; i >= 0; i--) {
      final ci = cands[i];
      if (ci.page == cj.page) continue;
      if (cj.page - ci.page > 12) break;
      if (ci.pos >= cj.pos || score[i] == double.negativeInfinity) continue;
      final ratio = (cum[cj.pos] - cum[ci.pos]) / ((cj.page - ci.page) * avg);
      final s = score[i] + cj.weight - 4 * math.pow(math.log(ratio), 2);
      if (s > score[j]) {
        score[j] = s;
        back[j] = i;
      }
    }
  }
  var best = 0;
  for (var j = 0; j < cands.length; j++) {
    if (score[j] > score[best] ||
        (score[j] == score[best] && cands[j].page > cands[best].page)) {
      best = j;
    }
  }
  final pos = List<int?>.filled(pages.length, null);
  for (var j = best; j >= 0; j = back[j]) {
    pos[cands[j].page] = cands[j].pos;
    if (back[j] < 0) break;
  }
  return pos;
}

String refText(TikkunWordRef r) =>
    '${TikkunData.booksOrder[r.book - 1]}:${r.chapter}:${r.verse}:${r.word}';

String dartString(String s) =>
    "'${s.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll(r'$', r'\$')}'";

/// The part of a table value that the text confirms at [wordIdx], or the raw
/// value when none does (a spelling that differs from the text).
String? confirmed(String? value, List<Word> words, int wordIdx) {
  if (value == null) return null;
  if (wordIdx >= 0 && wordIdx < words.length) {
    for (final part in parts(value)) {
      if (matchKey(part) == words[wordIdx].key) return part;
    }
  }
  return value;
}

void main() {
  test('generate torah layouts', () {
    final layouts = StringBuffer()
      ..writeln(_header)
      ..writeln('// dart format off')
      ..writeln()
      ..writeln('const Map<String, Object?> kTorahLayouts = {');
    final anchors = StringBuffer()
      ..writeln(_header)
      ..writeln('// dart format off')
      ..writeln()
      ..writeln(
        '/// עוגן כל עמוד: [חומש 1–5, פרק, פסוק, מילה בפסוק]; 0,0,0,0 = אין עוגן.',
      )
      ..writeln('const Map<String, List<int>> kTorahPageAnchors = {');
    final report = StringBuffer();

    for (final method in readSource()) {
      final pages = method.pages;
      final words = torahWords(TikkunTradition.forMethod(method.id));
      final pos = resolve(pages, words);

      layouts
        ..writeln('  ${dartString(method.id)}: {')
        ..writeln('    \'name\': ${dartString(method.name)},')
        ..writeln('    \'fullName\': ${dartString(method.fullName)},')
        ..writeln('    \'linesPerPage\': ${method.linesPerPage},')
        ..writeln('    \'pages\': [');
      anchors.writeln('  ${dartString(method.id)}: [');
      final missing = <String>[];
      final unconfirmed = <String>[];
      for (var p = 0; p < pages.length; p++) {
        final start = pos[p];
        var next = p + 1;
        while (next < pages.length && pos[next] == null) {
          next++;
        }
        final end = next < pages.length ? pos[next]! : words.length;
        final first = start == null
            ? pages[p].first
            : confirmed(pages[p].first, words, start);
        final last = next == p + 1
            ? confirmed(pages[p].last, words, end - 1)
            : pages[p].last;
        layouts.writeln(
          '      {\'num\': ${pages[p].num}, '
          '\'firstWord\': ${first == null ? 'null' : dartString(first)}, '
          '\'lastWord\': ${last == null ? 'null' : dartString(last)}},',
        );

        if (start == null) {
          anchors.writeln('    0, 0, 0, 0,');
          missing.add('p${p + 1}');
          continue;
        }
        final r = words[start].ref;
        anchors.writeln('    ${r.book}, ${r.chapter}, ${r.verse}, ${r.word},');

        if (p == 0) continue;
        // A boundary is confirmed when the previous page's last word sits
        // right before this page's first word; anything else is reported.
        final firstOk = parts(
          pages[p].first,
        ).any((w) => matchKey(w) == words[start].key);
        final lastOk = parts(
          pages[p - 1].last,
        ).any((w) => matchKey(w) == words[start - 1].key);
        if (!firstOk || !lastOk) {
          unconfirmed.add(
            'p${p + 1}@${refText(r)}'
            '${firstOk ? '' : ' first?'}${lastOk ? '' : ' last?'}',
          );
        }
      }
      layouts
        ..writeln('    ],')
        ..writeln('  },');
      anchors.writeln('  ],');
      report
        ..writeln(
          '${method.id}: ${pages.length} pages, '
          '${pages.length - missing.length} anchored',
        )
        ..writeln('  unanchored: $missing')
        ..writeln('  unconfirmed: $unconfirmed');
    }
    layouts.writeln('};');
    anchors.writeln('};');
    File(_layoutsOut).writeAsStringSync(layouts.toString());
    File(_anchorsOut).writeAsStringSync(anchors.toString());

    final dir = Platform.environment['ANCHORS_OUT'];
    if (dir != null) {
      File('$dir/anchors_report.txt').writeAsStringSync(report.toString());
    }
  });
}
