// אייקוני משפחות אלף (אותיות) וקישור של otzaria_icons, שמוגדלים בשורות תפריט.
//
// הרשימה מפורשת ולא נגזרת מ-`OtzariaIcons.allIcons`: הבדיקה
// plugin_icon_resolver_usage_test אוסרת התייחסות אליה מחוץ למפענחי האייקונים.
// הבדיקה menu_badge_icons_test מוודאת שכל אייקון כזה בספרייה נמצא כאן.

import 'package:flutter/widgets.dart';
import 'package:otzaria_icons/otzaria_icons.dart';

/// האם [icon] שייך למשפחת האותיות (`alef_*`, `beit*`, `tet*`) או הקישורים
/// (`link*`) של otzaria_icons.
bool isLetterOrLinkIcon(IconData icon) => _letterAndLinkIcons.contains(icon);

// IconData מגדיר ==, ולכן זה חייב להיות static final ולא const.
final Set<IconData> _letterAndLinkIcons = <IconData>{
  OtzariaIcons.alef_1_24_filled,
  OtzariaIcons.alef_1_24_regular,
  OtzariaIcons.alef_24_filled,
  OtzariaIcons.alef_24_regular,
  OtzariaIcons.alef_2_24_filled,
  OtzariaIcons.alef_2_24_regular,
  OtzariaIcons.alef_3_24_filled,
  OtzariaIcons.alef_3_24_regular,
  OtzariaIcons.alef_4_24_filled,
  OtzariaIcons.alef_4_24_regular,
  OtzariaIcons.alef_5_24_filled,
  OtzariaIcons.alef_5_24_regular,
  OtzariaIcons.alef_add_24_filled,
  OtzariaIcons.alef_add_24_regular,
  OtzariaIcons.alef_alef_24_filled,
  OtzariaIcons.alef_alef_24_regular,
  OtzariaIcons.alef_behind_alef_24_filled,
  OtzariaIcons.alef_behind_alef_24_regular,
  OtzariaIcons.alef_check_24_filled,
  OtzariaIcons.alef_check_24_regular,
  OtzariaIcons.alef_copy_24_filled,
  OtzariaIcons.alef_copy_24_regular,
  OtzariaIcons.alef_crown_24_filled,
  OtzariaIcons.alef_crown_24_regular,
  OtzariaIcons.alef_delete_24_filled,
  OtzariaIcons.alef_delete_24_regular,
  OtzariaIcons.alef_eraser_24_filled,
  OtzariaIcons.alef_eraser_24_regular,
  OtzariaIcons.alef_exclamation_24_filled,
  OtzariaIcons.alef_exclamation_24_regular,
  OtzariaIcons.alef_eye_24_filled,
  OtzariaIcons.alef_eye_24_regular,
  OtzariaIcons.alef_information_24_filled,
  OtzariaIcons.alef_information_24_regular,
  OtzariaIcons.alef_latin_a_24_filled,
  OtzariaIcons.alef_latin_a_24_regular,
  OtzariaIcons.alef_lips_24_filled,
  OtzariaIcons.alef_lips_24_regular,
  OtzariaIcons.alef_lock_24_filled,
  OtzariaIcons.alef_lock_24_regular,
  OtzariaIcons.alef_marker_24_filled,
  OtzariaIcons.alef_marker_24_regular,
  OtzariaIcons.alef_mix_24_filled,
  OtzariaIcons.alef_mix_24_regular,
  OtzariaIcons.alef_near_alef_24_filled,
  OtzariaIcons.alef_near_alef_24_regular,
  OtzariaIcons.alef_near_alef_rashi_24_filled,
  OtzariaIcons.alef_near_alef_rashi_24_regular,
  OtzariaIcons.alef_near_alef_stam_24_filled,
  OtzariaIcons.alef_near_alef_stam_24_regular,
  OtzariaIcons.alef_niqqud_24_filled,
  OtzariaIcons.alef_niqqud_24_regular,
  OtzariaIcons.alef_niqqud_taamim_24_filled,
  OtzariaIcons.alef_niqqud_taamim_24_regular,
  OtzariaIcons.alef_punctuation_24_filled,
  OtzariaIcons.alef_punctuation_24_regular,
  OtzariaIcons.alef_rashi_24_filled,
  OtzariaIcons.alef_rashi_24_regular,
  OtzariaIcons.alef_scissors_24_filled,
  OtzariaIcons.alef_scissors_24_regular,
  OtzariaIcons.alef_stam_24_filled,
  OtzariaIcons.alef_stam_24_regular,
  OtzariaIcons.alef_writing_24_filled,
  OtzariaIcons.alef_writing_24_regular,
  OtzariaIcons.beit_24_filled,
  OtzariaIcons.beit_24_regular,
  OtzariaIcons.beit_behind_alef_24_filled,
  OtzariaIcons.beit_behind_alef_24_regular,
  OtzariaIcons.beit_near_alef_24_filled,
  OtzariaIcons.beit_near_alef_24_regular,
  OtzariaIcons.link_24_filled,
  OtzariaIcons.link_24_regular,
  OtzariaIcons.link_add_24_filled,
  OtzariaIcons.link_add_24_regular,
  OtzariaIcons.link_alef_24_filled,
  OtzariaIcons.link_alef_24_regular,
  OtzariaIcons.link_book_24_filled,
  OtzariaIcons.link_book_24_regular,
  OtzariaIcons.link_check_24_filled,
  OtzariaIcons.link_check_24_regular,
  OtzariaIcons.link_copy_24_filled,
  OtzariaIcons.link_copy_24_regular,
  OtzariaIcons.link_delete_24_filled,
  OtzariaIcons.link_delete_24_regular,
  OtzariaIcons.link_document_24_filled,
  OtzariaIcons.link_document_24_regular,
  OtzariaIcons.link_eraser_24_filled,
  OtzariaIcons.link_eraser_24_regular,
  OtzariaIcons.link_exclamation_24_filled,
  OtzariaIcons.link_exclamation_24_regular,
  OtzariaIcons.link_eye_24_filled,
  OtzariaIcons.link_eye_24_regular,
  OtzariaIcons.link_information_24_filled,
  OtzariaIcons.link_information_24_regular,
  OtzariaIcons.link_marker_24_filled,
  OtzariaIcons.link_marker_24_regular,
  OtzariaIcons.link_quote_24_filled,
  OtzariaIcons.link_quote_24_regular,
  OtzariaIcons.link_scissors_24_filled,
  OtzariaIcons.link_scissors_24_regular,
  OtzariaIcons.links_24_filled,
  OtzariaIcons.links_24_regular,
  OtzariaIcons.tet_24_filled,
  OtzariaIcons.tet_24_regular,
  OtzariaIcons.tet_behind_tet_24_filled,
  OtzariaIcons.tet_behind_tet_24_regular,
  OtzariaIcons.tet_latin_t_24_filled,
  OtzariaIcons.tet_latin_t_24_regular,
  OtzariaIcons.tet_near_tet_24_filled,
  OtzariaIcons.tet_near_tet_24_regular,
  OtzariaIcons.tet_tet_24_filled,
  OtzariaIcons.tet_tet_24_regular,
};
