// GENERATED CODE — DO NOT MODIFY BY HAND.
// Generated by hook/build.dart on every Flutter build.
//
// אינדקס חיפוש מאוחד של ההגדרות. נוצר אוטומטית מתוך
// הצהרות `static const searchEntries` בקבצים תחת lib/settings/.

import 'package:otzaria/settings/search/settings_search_models.dart';
import 'package:otzaria/settings/panels/calendar_settings_panel.dart';
import 'package:otzaria/settings/panels/gematria_settings_panel.dart';
import 'package:otzaria/settings/tabs/about_dev_tab.dart';
import 'package:otzaria/settings/tabs/design_settings_tab.dart';
import 'package:otzaria/settings/tabs/library_settings_tab.dart';
import 'package:otzaria/settings/tabs/shortcuts_settings_tab.dart';
import 'package:otzaria/settings/tabs/system_settings_tab.dart';
import 'package:otzaria/settings/tabs/text_settings_tab.dart';

/// כל פריטי החיפוש שנאספו מהטאבים והפנלים.
const List<SettingsSearchEntry> kGeneratedSettingsSearchEntries = [
  ...AboutDevTab.searchEntries,
  ...DesignSettingsTab.searchEntries,
  ...LibrarySettingsTab.searchEntries,
  ...ShortcutsSettingsTab.searchEntries,
  ...SystemSettingsTab.searchEntries,
  ...TextSettingsTab.searchEntries,
  ...CalendarSettingsTab.searchEntries,
  ...GematriaSettingsTab.searchEntries,
];
