; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "אוצריא"
#define MyAppVersion "0.9.90"
#define MyAppPublisher "sivan22"
#define MyAppURL "https://github.com/otzaria/otzaria"
#define MyAppExeName "otzaria.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{EEC4F712-CD05-4D15-A753-509E840A51A5}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
PrivilegesRequiredOverridesAllowed=dialog
DefaultDirName={code:GetDefaultInstallDir}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
OutputDir=.
OutputBaseFilename=otzaria-{#MyAppVersion}-windows-full
SetupIconFile=white_sketch128x128.ico
Compression=lzma
SolidCompression=yes
; Disable compression for DLL files to prevent corruption
CompressionThreads=1
WizardStyle=modern
DisableDirPage=no

[InstallDelete]
; מחיקת ספריית נתונים ישנה לפני פריסת מסד הנתונים החדש
Type: filesandordirs; Name: "{code:GetDataDir}\books"

[Dirs]
Name: "{code:GetDataDir}"; Permissions: users-modify
Name: "{code:GetDataDir}\books"; Permissions: users-modify
Name: "{code:GetDataDir}\index"; Permissions: users-modify

[Languages]
Name: "hebrew"; MessagesFile: "compiler:Languages\Hebrew.isl"

[Code]

function TryGetInstallDirFromRegistry(RootKey: Integer; const SubKey: String; var InstallDir: String): Boolean;
begin
  Result := RegQueryStringValue(RootKey, SubKey, 'Inno Setup: App Path', InstallDir);
  if (not Result) or (InstallDir = '') then
    Result := RegQueryStringValue(RootKey, SubKey, 'InstallLocation', InstallDir);

  if Result and DirExists(InstallDir) then
    exit;

  InstallDir := '';
  Result := False;
end;

function FindPreviousInstallDir(): String;
var
  InstallDir: String;
  LegacyDir: String;
  UninstallKey: String;
begin
  UninstallKey := 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{EEC4F712-CD05-4D15-A753-509E840A51A5}_is1';

  if TryGetInstallDirFromRegistry(HKLM64, UninstallKey, InstallDir) or
     TryGetInstallDirFromRegistry(HKCU, UninstallKey, InstallDir) then
  begin
    Result := InstallDir;
    exit;
  end;

  LegacyDir := 'C:\אוצריא';
  if DirExists(LegacyDir) then
  begin
    Result := LegacyDir;
    exit;
  end;

  LegacyDir := ExpandConstant('{autopf}\אוצריא');
  if DirExists(LegacyDir) then
  begin
    Result := LegacyDir;
    exit;
  end;

  LegacyDir := ExpandConstant('{autopf}\Otzaria');
  if DirExists(LegacyDir) then
  begin
    Result := LegacyDir;
    exit;
  end;

  Result := '';
end;

function GetDefaultInstallDir(Param: String): String;
begin
  Result := FindPreviousInstallDir();
  if Result = '' then
    Result := ExpandConstant('{autopf}\אוצריא');
end;

function GetDataDir(Param: String): String;
begin
  if IsAdminInstallMode then
    Result := ExpandConstant('{commonappdata}\otzaria')
  else
    Result := ExpandConstant('{userappdata}\otzaria');
end;

function InitializeSetup(): Boolean;
var
  DataPath, OldPath: String;
begin
  Result := True;
  DataPath := GetDataDir('');
  OldPath := 'C:\אוצריא';
  
  // בדיקה אם יש התקנה ישנה בנתיב העברי
  if DirExists(OldPath) then
  begin
    if MsgBox('נמצאה התקנה ישנה ב-' + OldPath + #13#10 +
              'ספריית הספרים עוברת לנתיב חדש: ' + DataPath + #13#10#13#10 +
              'האם להעביר את הנתונים למיקום החדש?',
              mbConfirmation, MB_YESNO) = IDYES then
    begin
      // המשתמש יצטרך להעביר ידנית או שנוסיף קוד העברה
      MsgBox('לאחר ההתקנה, תוכל להעביר את הנתונים מ-' + OldPath + ' ל-' + DataPath, mbInformation, MB_OK);
    end;
  end;
  
  // בדיקה אם התיקיות קיימות והצגת אזהרה
  if DirExists(DataPath + '\books') then
  begin
    if MsgBox('שים לב: קיימים נתונים מספרייה ישנה בתיקייה ' + DataPath + '\books' + #13#10 +
              'הקודמים יימחקו ויוחלפו בנתוני ההתקנה החדשה.' + #13#10#13#10 +
              'האם להמשיך בהתקנה?',
              mbConfirmation, MB_YESNO) = IDNO then
    begin
      Result := False;
    end;
  end;
end;

// ─── בדיקות רכיבי מערכת ───────────────────────────────────────────────────

function GetVCVersion: String;
var
  Version: String;
begin
  if RegQueryStringValue(HKLM64,
      'SOFTWARE\Microsoft\VisualStudio\14.0\VC\Runtimes\x64',
      'Version', Version) then
    Result := Version
  else
    Result := '';
end;

function GetWebView2Version: String;
var
  Version: String;
begin
  if RegQueryStringValue(HKLM64,
      'SOFTWARE\WOW6432Node\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}',
      'pv', Version) then
  begin
    Result := Version;
    exit;
  end;
  if RegQueryStringValue(HKCU,
      'SOFTWARE\Microsoft\EdgeUpdate\Clients\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}',
      'pv', Version) then
    Result := Version
  else
    Result := '';
end;

function VCRedistNeedsInstall: Boolean;
begin
  Result := GetVCVersion = '';
end;

function WebView2NeedsInstall: Boolean;
begin
  Result := GetWebView2Version = '';
end;

// ─── משתנים גלובליים לבחירת רכיבים ────────────────────────────────────────

var
  CompPage: TWizardPage;
  VCCheck, WV2Check: TCheckBox;
  VCLabel, WV2Label: TLabel;
  InstallVC, InstallWV2: Boolean;

// ─── בניית עמוד בחירת רכיבים ───────────────────────────────────────────────

procedure CreateComponentsPage;
var
  VCVersion, WV2Version: String;
  VCStatus, WV2Status: String;
  VCColor, WV2Color: TColor;
  TopY: Integer;
  HeaderLabel: TLabel;
begin
  CompPage := CreateCustomPage(wpSelectDir,
    'בחירת רכיבי מערכת להתקנה',
    'בדיקת הרכיבים הנדרשים לאפליקציה');

  VCVersion  := GetVCVersion;
  WV2Version := GetWebView2Version;

  // כותרת הסבר
  HeaderLabel := TLabel.Create(CompPage);
  HeaderLabel.Parent := CompPage.Surface;
  HeaderLabel.Left   := 0;
  HeaderLabel.Top    := 0;
  HeaderLabel.Width  := CompPage.SurfaceWidth;
  HeaderLabel.AutoSize := False;
  HeaderLabel.WordWrap := True;
  HeaderLabel.Caption :=
    'להלן רכיבי המערכת הנדרשים לפעולת אוצריא.' + #13#10 +
    'רכיבים המסומנים באדום חסרים ונדרשים להתקנה. ' +
    'רכיבים ירוקים קיימים ואינם דורשים פעולה.';
  HeaderLabel.Height := 40;

  TopY := 55;

  // ─── Visual C++ Runtime ───────────────────────────────────────────────────
  VCCheck := TCheckBox.Create(CompPage);
  VCCheck.Parent  := CompPage.Surface;
  VCCheck.Left    := 0;
  VCCheck.Top     := TopY;
  VCCheck.Width   := CompPage.SurfaceWidth;
  VCCheck.Caption := 'Visual C++ Redistributable 2022 (x64)';

  if VCVersion = '' then
  begin
    VCStatus := '⚠ חסר — נדרשת התקנה! ללא רכיב זה האפליקציה לא תפעל.';
    VCColor  := clRed;
    VCCheck.Checked := True;
    VCCheck.Enabled := False;  // חובה — לא ניתן לבטל
  end
  else
  begin
    VCStatus := '✓ קיים (גרסה: ' + VCVersion + ') — לא נדרשת פעולה.';
    VCColor  := $006400;  // ירוק כהה
    VCCheck.Checked := False;
    VCCheck.Enabled := False;  // קיים — נעול כדי למנוע התקנה מיותרת
  end;

  VCLabel := TLabel.Create(CompPage);
  VCLabel.Parent   := CompPage.Surface;
  VCLabel.Left     := 20;
  VCLabel.Top      := TopY + 22;
  VCLabel.Width    := CompPage.SurfaceWidth - 20;
  VCLabel.AutoSize := False;
  VCLabel.WordWrap := True;
  VCLabel.Caption  := VCStatus;
  VCLabel.Font.Color := VCColor;
  VCLabel.Height   := 30;

  TopY := TopY + 70;

  // ─── WebView2 Runtime ─────────────────────────────────────────────────────
  WV2Check := TCheckBox.Create(CompPage);
  WV2Check.Parent  := CompPage.Surface;
  WV2Check.Left    := 0;
  WV2Check.Top     := TopY;
  WV2Check.Width   := CompPage.SurfaceWidth;
  WV2Check.Caption := 'Microsoft WebView2 Runtime';

  // WebView2 אינו חובה — משמש רק למערכת הפלאגינים (לא לקריאה/חיפוש/סימניות)
  if WV2Version = '' then
  begin
    WV2Status := '⚠ חסר — מומלץ להתקין. ללא רכיב זה מערכת הפלאגינים לא תפעל,' +
                 ' אך שאר האפליקציה תעבוד כרגיל.';
    WV2Color  := $007FFF;  // כתום — אזהרה, לא שגיאה ($BBGGRR: B=00, G=7F, R=FF)
    WV2Check.Checked := True;
    WV2Check.Enabled := True;  // אופציונלי — ניתן לבטל
  end
  else
  begin
    WV2Status := '✓ קיים (גרסה: ' + WV2Version + ') — לא נדרשת פעולה.';
    WV2Color  := $006400;
    WV2Check.Checked := False;
    WV2Check.Enabled := False;  // קיים — נעול כדי למנוע התקנה מיותרת
  end;

  WV2Label := TLabel.Create(CompPage);
  WV2Label.Parent   := CompPage.Surface;
  WV2Label.Left     := 20;
  WV2Label.Top      := TopY + 22;
  WV2Label.Width    := CompPage.SurfaceWidth - 20;
  WV2Label.AutoSize := False;
  WV2Label.WordWrap := True;
  WV2Label.Caption  := WV2Status;
  WV2Label.Font.Color := WV2Color;
  WV2Label.Height   := 30;
end;

function ShouldInstallVC: Boolean;
begin
  Result := InstallVC;
end;

function ShouldInstallWV2: Boolean;
begin
  Result := InstallWV2;
end;

procedure InitializeWizard;
begin
  // אתחול ברירות מחדל: מתקין רק אם חסר
  InstallVC  := VCRedistNeedsInstall;
  InstallWV2 := WebView2NeedsInstall;
  CreateComponentsPage;
end;

// שמירת בחירות המשתמש בלחיצה על "הבא" מדף הרכיבים
function NextButtonClick(CurPageID: Integer): Boolean;
begin
  Result := True;
  if (CompPage <> nil) and (CurPageID = CompPage.ID) then
  begin
    InstallVC  := VCCheck.Checked;
    InstallWV2 := WV2Check.Checked;
  end;
end;

procedure ExtractBundledDatabase(const ArchiveName, DatabaseName: String);
var
  ArchivePath, DatabasePath, ZstdPath, Params: String;
  ResultCode: Integer;
begin
  ArchivePath := ExpandConstant('{app}\_staging\' + ArchiveName);
  if not FileExists(ArchivePath) then
  begin
    Log('Bundled database archive not found, skipping: ' + ArchivePath);
    exit;
  end;

  DatabasePath := ExpandConstant('{code:GetDataDir}\books\' + DatabaseName);
  ZstdPath := ExpandConstant('{app}\zstd.exe');

  ForceDirectories(ExtractFileDir(DatabasePath));

  Log('Extracting bundled database from ' + ArchivePath);
  Params := '-d -f -T0 --long=31 "' + ArchivePath + '" -o "' + DatabasePath + '"';

  if (not Exec(ZstdPath, Params, '', SW_HIDE, ewWaitUntilTerminated, ResultCode)) or (ResultCode <> 0) then
  begin
    MsgBox('חילוץ מסד הנתונים נכשל. קוד יציאה: ' + IntToStr(ResultCode), mbCriticalError, MB_OK);
    Abort;
  end;

  DeleteFile(ArchivePath);
end;

procedure ExtractBundledTarArchive(const ArchiveName, TargetDirName: String);
var
  ArchivePath, TarPath, ParentDir, TargetDir, ZstdPath, SevenZipPath, Params: String;
  ResultCode: Integer;
begin
  ArchivePath := ExpandConstant('{app}\_staging\' + ArchiveName);
  if not FileExists(ArchivePath) then
  begin
    Log('Bundled archive not found, skipping: ' + ArchivePath);
    exit;
  end;

  ParentDir := ExpandConstant('{code:GetDataDir}\books');
  TarPath := ParentDir + '\' + ChangeFileExt(ArchiveName, '');
  TargetDir := ExpandConstant('{code:GetDataDir}\books\' + TargetDirName);
  ZstdPath := ExpandConstant('{app}\zstd.exe');
  SevenZipPath := ExpandConstant('{app}\7za.exe');

  if DirExists(TargetDir) then
  begin
    DelTree(TargetDir, True, True, True);
  end;

  Log('Extracting bundled tar archive from ' + ArchivePath);
  Params := '-d -f -T0 --long=31 "' + ArchivePath + '" -o "' + TarPath + '"';

  if (not Exec(ZstdPath, Params, '', SW_HIDE, ewWaitUntilTerminated, ResultCode)) or (ResultCode <> 0) then
  begin
    MsgBox('חילוץ ארכיון ה-PDF נכשל. קוד יציאה: ' + IntToStr(ResultCode), mbCriticalError, MB_OK);
    Abort;
  end;

  Params := 'x -y "' + TarPath + '" "-o' + ParentDir + '"';
  if (not Exec(SevenZipPath, Params, '', SW_HIDE, ewWaitUntilTerminated, ResultCode)) or
     (ResultCode <> 0) then
  begin
    MsgBox('פתיחת ארכיון ה-PDF נכשלה. קוד יציאה: ' + IntToStr(ResultCode), mbCriticalError, MB_OK);
    Abort;
  end;

  DeleteFile(TarPath);
  DeleteFile(ArchivePath);
  // Optional: Delete the bundled db directory since everything was extracted elsewhere
  // But maybe it's cleaner to handle this in a separate procedure if needed.
end;

procedure CurStepChanged(CurStep: TSetupStep);
var
  ZstdPath, SevenZipPath: String;
  AppDataPath: string;
begin
  if CurStep = ssInstall then
  begin
    if WizardIsTaskSelected('resetsettings') then
    begin
      AppDataPath := GetDataDir('');
      if DirExists(AppDataPath) then
        DelTree(AppDataPath, True, True, True);

      AppDataPath := ExpandConstant('{userappdata}\otzaria');
      if DirExists(AppDataPath) then
        DelTree(AppDataPath, True, True, True);

      AppDataPath := ExpandConstant('{commonappdata}\otzaria');
      if DirExists(AppDataPath) then
        DelTree(AppDataPath, True, True, True);

      AppDataPath := ExpandConstant('{localappdata}\otzaria');
      if DirExists(AppDataPath) then
        DelTree(AppDataPath, True, True, True);
        
      // Delete old settings and personal notes (in AppData/Roaming)
      AppDataPath := ExpandConstant('{userappdata}\com.example');
      if DirExists(AppDataPath) then
        DelTree(AppDataPath, True, True, True);
    end;
  end;

  if CurStep <> ssPostInstall then
    exit;

  ZstdPath := ExpandConstant('{app}\zstd.exe');
  SevenZipPath := ExpandConstant('{app}\7za.exe');

  if not FileExists(ZstdPath) then
  begin
    MsgBox('קובץ החילוץ zstd.exe לא נמצא. ההתקנה לא יכולה לחלץ את קבצי הספרייה המצורפים.', mbCriticalError, MB_OK);
    Abort;
  end;

  if not FileExists(SevenZipPath) then
  begin
    MsgBox('קובץ החילוץ 7za.exe לא נמצא. ההתקנה לא יכולה לחלץ את קבצי ה-PDF המצורפים.', mbCriticalError, MB_OK);
    Abort;
  end;

  ExtractBundledDatabase('seforim.db.zst', 'seforim.db');
  ExtractBundledDatabase('otzar-HB_catalog.db.zst', 'otzar-HB_catalog.db');
  ExtractBundledTarArchive('talmud_bavli_latest.tar.zst', 'תלמוד בבלי');
  DeleteFile(ZstdPath);
  DeleteFile(SevenZipPath);
  
  // Cleanup the temporary extraction directory
  DelTree(ExpandConstant('{app}\_staging'), True, True, True);
end;

[Run]
Filename: "{tmp}\vc_redist.x64.exe"; Parameters: "/install /quiet /norestart"; StatusMsg: "מתקין Visual C++ Redistributable 2022..."; Flags: waituntilterminated; Check: ShouldInstallVC
Filename: "{tmp}\MicrosoftEdgeWebview2Setup.exe"; Parameters: "/silent /install"; StatusMsg: "מתקין Microsoft WebView2 Runtime..."; Flags: waituntilterminated; Check: ShouldInstallWV2
Filename: "{app}\{#MyAppExeName}"; Description: "הפעל את {#MyAppName}"; Flags: nowait postinstall skipifsilent

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "resetsettings"; Description: "איפוס הגדרות משתמש והסרת התקנות קודמות (מומלץ למעדכנים מגרסה < 0.9.80, שים לב: זה ימחק הערות אישיות!)"; Flags: unchecked

[Files]
; Copy DLL files without compression to prevent corruption
Source: "..\build\windows\x64\runner\Release\*.dll"; DestDir: "{app}"; Flags: ignoreversion nocompression
; Copy all other app files
Source: "..\build\windows\x64\runner\Release\*"; \
  Excludes: "*.dll"; \
    DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

; Copy compressed library assets and extraction tool for post-install extraction
Source: "library_db\seforim.db.zst"; DestDir: "{app}\_staging"; Flags: ignoreversion nocompression
Source: "library_db\otzar-HB_catalog.db.zst"; DestDir: "{app}\_staging"; Flags: ignoreversion nocompression
Source: "library_db\talmud_bavli_latest.tar.zst"; DestDir: "{app}\_staging"; Flags: ignoreversion nocompression
Source: "zstd.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "7za.exe"; DestDir: "{app}"; Flags: ignoreversion

; vc_redist.x64.exe — הגרסה הרשמית של Microsoft, כ-25MB במקום AIO (~50MB)
; כוללת את 2015/2017/2019/2022 תחת אותו מספר גרסה (14.x)
Source: "vc_redist.x64.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall; Check: VCRedistNeedsInstall
; MicrosoftEdgeWebview2Setup.exe — bootstrapper קטן (~2MB) שמוריד ומתקין WebView2
; נדרש על ידי flutter_inappwebview_windows; ב-Win10/11 עם Edge עדכני — כבר קיים
Source: "MicrosoftEdgeWebview2Setup.exe"; DestDir: "{tmp}"; Flags: deleteafterinstall; Check: WebView2NeedsInstall

[INI]
Filename: "{app}\system_install.marker"; Section: "Install"; Key: "Mode"; String: "Admin"; Check: IsAdminInstallMode
